name: On New Release

on:
  repository_dispatch:
    types: [lsp-add-or-update-package]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - id: make-pr
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD" | python3 auto-update-repository.py
      - uses: peter-evans/create-pull-request@v8
        with:
          commit-message: '${{ steps.make-pr.outputs.commit_message }}'
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          delete-branch: true
          branch-suffix: random
          title: '${{ steps.make-pr.outputs.pr_title }}'
          body: '${{ steps.make-pr.outputs.pr_body }}'
