name: On PR Report

on:
  workflow_run:
    workflows: ["On PR"]  # must match the name of on-pull-request.yml
    types: [completed]

jobs:
  post-review:
    if: ${{ github.event.workflow_run.conclusion != 'skipped' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      actions: read
      contents: read
    steps:
      - name: Post PR comment from artifact
        uses: kaste/st_package_reviewer/gh_action@406c008ab8551a3eda62c5388bdd0ab1dba5e9f9 # v1.3.12-5-g406c008
        with:
          phase: report
