name: On PR

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - repository.json
  issue_comment:
    types: [created]  # run on "/review" comment

jobs:
  # Review phase only. The comment is posted by on-pull-request-report.yml.
  # Runs on non-draft PR events, or on demand via a PR comment.
  package:
    if: >-
      ${{
        (github.event_name == 'pull_request' && !github.event.pull_request.draft) ||
        (
          github.event_name == 'issue_comment' &&
          github.event.issue.pull_request != null && contains(github.event.comment.body, '/review')
        )
      }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # needed to react to "/review" comments on PRs
    steps:
      - name: Check out additional LSP checks
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: sublimelsp/lsp-package-reviewer-checks
          ref: bd467ce55ed69cd398e31681502d629ae17c3144
          path: lsp-package-reviewer-checks

      - name: Diff and review changed/added packages
        uses: kaste/st_package_reviewer/gh_action@406c008ab8551a3eda62c5388bdd0ab1dba5e9f9 # v1.3.12-5-g406c008
        with:
          pr: ${{ github.event.pull_request.html_url || github.event.issue.pull_request.html_url }}
          file: repository.json
          add-file-checkers: lsp-package-reviewer-checks/lsp_review_checks
          exclude: CheckSettingsMenuEntry
