name: On PR Report

on:
  workflow_run:
    workflows: ["On PR"]  # must match the name of on-pull-request.yml
    types: [completed]

jobs:
  post-review:
    if: ${{ github.event.workflow_run.conclusion != 'skipped' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      actions: read
      contents: read
    steps:
      - name: Post PR comment from artifact
        uses: kaste/st_package_reviewer/gh_action@d3263da7c96cb831b52bf4a7323ab372bd23d461 # v1.3.12
        with:
          phase: report
