name: On PR

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  issue_comment:
    types: [created]  # run on "/review" comment

permissions:
  contents: read
  pull-requests: read
  issues: write  # needed for issue-comment acknowledgements

jobs:
  # Review phase only. The comment is posted by on-pull-request-report.yml.
  # Runs on non-draft PR events, or on demand via a PR comment with "📦" or "/review".
  package:
    if: >-
      ${{
        (github.event_name == 'pull_request' && !github.event.pull_request.draft) ||
        (
          github.event_name == 'issue_comment' &&
          github.event.issue.pull_request != null && contains(github.event.comment.body, '/review')
        )
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Diff and review changed/added packages
        uses: kaste/st_package_reviewer/gh_action@1d97146eb6ff2986c67195123a9a6cfaf7776cdd # v1.3.11
        with:
          pr: ${{ github.event.pull_request.html_url || github.event.issue.pull_request.html_url }}
          file: repository.json
