name: Schema test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: packagecontrol/st-schema-reviewer-action@aa8d4a69fb7122c703edfc7571f5cd6c12b488fd
